name: Update Index Page Daily
on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias às 00:00 UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Atualizar HTML com data do Apps Script
        run: |
          curl -s "https://script.google.com/macros/s/SEU_CÓDIGO_DO_APP/exec" > data.json
          TITLE=$(jq -r .title data.json)
          DESCRIPTION=$(jq -r .description data.json)
          echo "<!DOCTYPE html>
          <html lang='pt-BR'>
          <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <meta name='robots' content='index, follow'>
              <title>$TITLE</title>
              <meta name='description' content='$DESCRIPTION'>
          </head>
          <body>
              <h1>$TITLE</h1>
              <p>$DESCRIPTION</p>
          </body>
          </html>" > index.html

      - name: Commit e push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Atualizando data da página para $(date +'%d/%m/%Y')" || echo "Nada a atualizar"
          git push
